### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by RFlintstone** [eliangerard/text-to-mp3#1]
Pretty much what I was looking for! 
Few questions though:
- Which languages are supported? I'm looking for an english (male) voice, either US or Australian
- Is there a way to play the sounds on the background? Right now, they appear on top of everything else.

**Comment by eliangerard** [comment]
Hi! Thank you for using this package. I have just added a page in the wiki where you can see the supported languages, which you can check out [here](https://github.com/eliangerard/simple-tts-mp3/wiki). Unfortunately, since this package works with Google Translate's TTS, it doesn't allow changing the gender of the voice. 
Regarding the background sounds, what do you specifically mean? At the moment, there is no way to adjust the volume or positioning of the audio through the package.
Thanks again!
